### ISSUE TITLE
choose a static site generator

### ISSUE THREAD

**Issue by danbjoseph** [posm/docs#1]
- will host the docs content of both [Portable OpenStreetMap (POSM)](https://github.com/posm/posm.github.io) and [OpenMapKit (OMK)](https://github.com/posm/OpenMapKitWebsite)
- the sites are currently live at http://posm.io/ and http://openmapkit.org/
- i like http://www.mkdocs.org/ and https://docsify.js.org/ but there are plenty of options out there
    - what are any major differences in the functionalities?
    - i’m not worried about duplicating the appearance of the landing/home page of the OMK site, just the http://openmapkit.org/docs.html material needs to be ported over
    - the POSM site is not at all mobile friendly and does have a very extendable layout (for example, limited in the number of topics that can be added to the top nav bar)

**Comment by twmedlin** [comment]
**Current Requirements** 

Requirements  |  Priority
------------ |---------
Supports Markdown |  
Supports flexible website structures   |    
Adoption by open-source community |   
Implemented in technology with some level of in-house experience  |      
Supports GitHub pages    |      
Generates Static Site    |     

1. Requirements from conversation with @danbjoseph on Friday, March 9

**Comment by danbjoseph** [comment]
went with [sphinx](http://www.sphinx-doc.org/en/master/) for now
