### ISSUE TITLE
add to documentation: how to access admin features

### ISSUE THREAD

**Issue by sethfitz** [posm/docs#10]
As of the upcoming 0.8.0 release of POSM (via posm/posm-admin-ui@2.2.0), the admin sidebar does not include links to "admin" functionality by default.

To access general-purpose admin functionality (backups at the moment), go directly to http://posm.io/posm/admin.

To access network settings, go directly to http://posm.io/posm/settings.

To include links to admin functionality, edit `/opt/posm-www/config.json` and remove `"showAdmin": false,`.

Alternately, set `posm_show_admin=true` in `kickstart/etc/settings` prior to installation (only relevant when installing from source).

**Comment by danbjoseph** [comment]
@mojodna,  could you alternatively set `"showAdmin": true,`?

**Comment by danbjoseph** [comment]
nvm, needed to read the next line.
