### ISSUE TITLE
add to docs: how to get OSM data edited on the POSM off

### ISSUE THREAD

**Issue by danbjoseph** [posm/docs#13]
if i've had people edit the local OSM db on the POSM via the iD editor. how do i then get it off?

also, are there enough details about POSM replay tool?

**Comment by sethfitz** [comment]
Good question. I'm not sure this has ever come up. Potential options:

1. download a snapshot of current data from the API querying the full AOI bounds - if done in JOSM, this can be loaded into a layer and either saved out or individual features copied into an OSM-backed layer
2. download OSC changes for each edit made (this is what the POSM Replay Tool does)
3. generate an OSM XML / PBF dump using Osmosis against the API DB (using the command line)
4. generate an OSM XML history dump using [planet-dump-ng](https://github.com/zerebubuth/planet-dump-ng) against `pg_dump` output (using the command line)
5. gather minutely diffs from http://posm.io/replication/ (these are used for updating the rendering database)

[Merging Offline Edits with the POSM Replay Tool](https://hi.stamen.com/merging-offline-edits-with-the-posm-replay-tool-2f39a4410d2a) and https://github.com/posm/posm-replay-tool contain the extent of documentation about the replay tool. I don't think this is sufficient, but I'm also only aware of 2 times that it's been used (edge cases surfaced on the second, so I would expect more). 🐔 and 🥚, I suppose.
